### ISSUE TITLE
Can't open the project on Firefox

### ISSUE THREAD

**Issue by Siclol** [Jaspero/fireshop#110]
I get a blank page with the following error messages:

![Screen Shot 2019-05-06 at 3 34 02 PM](https://user-images.githubusercontent.com/21045225/57228635-8f755900-7014-11e9-8682-9328f7a91baf.png)

**Comment by svendjanis** [comment]
https://support.mozilla.org/bs/kb/how-do-you-use-google-firebase-firefox maybe this will help a litlle

**Comment by Siclol** [comment]
Closing for now. It only seems to be an issue on iOs Firefox.
