### ISSUE TITLE
Dashboard Page

### ISSUE THREAD

**Issue by flauc** [Jaspero/fireshop#14]
We need to decide on what to put on the dashboard. I'm thinking showing income and new customers in the last month might be a good start and possibly a table with the most recent orders

**Comment by Siclol** [comment]
We definitely need a "Get started" section on the dashboard for new users. I think we should start with that.

**Comment by Siclol** [comment]
@flauc I've added placeholders for graphs and hard-coded recent orders. They need to be connected.

**Comment by flauc** [comment]
@svendjanis 

- [ ] Let's pull in the 3 latest orders for that order card and show an empty state if there aren't any. 
- [ ] Let's pull in a single category,product and discount to see if we should check any of the items in the first card
- [ ] Let's create a query for orders in the last month. This will be a beginning for drawing graphs
