### ISSUE TITLE
Order Single Updates

### ISSUE THREAD

**Issue by flauc** [Jaspero/fireshop#148]
- [x] CreatedOn shouldn't be a form field
- [x] We have two fields for customerId and customerName when we should actually have just a single field for customer select and if one is selected we populate both properties on save.
- [x] OrderItems should be adjusted according to the new interface
- [x] paymentIntentId should only be viewable and that only on update 
- [x] We shouldn't have a field for the price it should be automatically populated from the order items added
- [x] if a customer is selected we should try and prepopulate the billing/shipping

**Comment by koleCar** [comment]
@Siclol we need style on orders-single-page and modal
