### ISSUE TITLE
label:bug Functions: Your functions could not be parsed due to an issue with your node_modules

### ISSUE THREAD

**Issue by SofianeBoumedine** [Jaspero/fireshop#187]
*Env*

- Windows10
- Visual Studio Code
- Git
- Node 10
- Firebase
- Firebase-tools

**Step to produce**
- Config env with command
- Change .firebaserc
- Firebase deploy/firebase serve

**Comment by flauc** [comment]
I think this is because our functions actually run on node v8, but now is as good a time as any to update to v10.
