### ISSUE TITLE
Access to platform denied. Please contact an administrator.

### ISSUE THREAD

**Issue by walqid** [Jaspero/fireshop#198]
I'm unable to login as an administrator to the dashboard, despite being sign up and having added the document "allowed-admins" to the settings collection in firestore and setting the "email" property.

Error appears in snackbar / dashboard login page:

> Access to platform denied. Please contact an administrator.

PS: Initial diagnosis on my deployment indicates that the userCreated function is not being triggered as it should, while other functions like userDeleted do.

**Comment by flauc** [comment]
@walqid I wasn't able to recreate this. Is it possible that you first created an account and then added the allowed-admins document? Because if you did, that document is required to be in place before creating an account.

**Comment by walqid** [comment]
@flauc I was able to resolve the issue by creating the document "settings > user > roles[]" and setting my email address before signing up. I haven't ended up adding the "allowed-admins" document as I have found no implementation of a call to that document in the code.

**Comment by flauc** [comment]
Yes, I'm sorry @walqid the documentation needed to be updated. Thank you for reporting everything you find.
