### ISSUE TITLE
Error loading image

### ISSUE THREAD

**Issue by ivanshero** [Jaspero/fireshop#222]
Product images are not displayed correctly .

When change the image link from Firebase it is displayed , and images that are added from Admin page are not displayed on the shop!

**Comment by AntonioStipic** [comment]
@ivanshero Hello! Could you provide a little bit more details on what issues you are experiencing since our tests showed no errors.

**Comment by ivanshero** [comment]
Here is a [screenshot](https://firebasestorage.googleapis.com/v0/b/king-brothers-web.appspot.com/o/%E2%80%8F%E2%80%8F%D9%84%D9%82%D8%B7%D8%A9%20%D8%A7%D9%84%D8%B4%D8%A7%D8%B4%D8%A9%20(16).png?alt=media&token=3686ed61-f8af-4e03-a929-11ae744d4c41) of the Shop page , the image does not load .

Here is the [link ](https://firebasestorage.googleapis.com/v0/b/king-brothers-web.appspot.com/o/products-en-fashion-gfggggggggggggggggg.jpg?alt=media&token=d612a212-0cb2-4f27-b7db-8b75f9b959ba)uploaded by the Dashboard.

Is there a specific way to get the image link or any procedures to do it!

**Comment by flauc** [comment]
@ivanshero the issue you're probably seeing is CORS preventing the image from loading. Did you do the last step described in the readme?

https://github.com/Jaspero/fireshop#setup

**Comment by AntonioStipic** [comment]
@ivanshero You may be experiencing issues for one of the following reasons:

- Firebase Functions have not been deployed. [Details here](https://firebase.google.com/docs/functions/manage-functions)
- CORS configuration has not been added to your storage bucket. [Details here](https://github.com/Jaspero/fireshop#setup)

**Comment by ivanshero** [comment]
I think the reason is to upload the same image twice in one product.
I tried to upload a product with different images and it succeeded, but when I selected the same image twice the image was not uploaded to the site.
