### ISSUE TITLE
Credentials for the example deployment of CMS doesn't work

### ISSUE THREAD

**Issue by warlock2k** [Jaspero/fireshop#292]
<html>
<body>

Site | https://fireshop.admin.jaspero.co
-- | --
Email | example@jaspero.co
Password | example

</body>
</html>

Can you help with this?

**Comment by flauc** [comment]
@warlock2k I'll close this one as well. Apologies for the confusion, let us know on https://github.com/Jaspero/jms if you choose to use it and we'll do our best to help.

**Comment by warlock2k** [comment]
@flauc I will, thank you so much.
