### ISSUE TITLE
Documentation for setup

### ISSUE THREAD

**Issue by warlock2k** [Jaspero/fireshop#293]
The current documentation seems limited and a typical new user may find it difficult to run and set this project up. Is there a chance for this to be improved?

**Comment by warlock2k** [comment]
Please provide node, npm and angular versions for running this project

**Comment by warlock2k** [comment]
How must the database look like? Currently, there seems to be no way I can replicate it on my firebase account.

Could someone please guide me on where I can add currencies as of today?

**Comment by flauc** [comment]
hi @warlock2k unfortunately this project is a bit outdated and we're no longer sure what changes are needed to make it work with the latest firebase updates. 

I would suggest looking at: https://github.com/Jaspero/jms

And this flavor specifically:
https://github.com/Jaspero/jms/tree/flavor/static-svelte

It doesn't have payments by default so a stripe integration would need to be built out but everything else would be there. 

The documentation as well is a bit more built out:
https://github.com/Jaspero/jms/wiki

**Comment by warlock2k** [comment]
@flauc Thank you for responding, I will check them out.
