### ISSUE TITLE
Stripe integration 

### ISSUE THREAD

**Issue by koleCar** [Jaspero/fireshop#41]
1. Functions endpoint for creating a payment intent 
2. Call endpoint when lending on checkout and send items
3. Handle client payment.
4. Handle payment result with a webhook.

**Comment by flauc** [comment]
@koleCar 

- Hide header and theme selector when on checkout to eliminate distractions
- Connect logged in / guest checkout 
- Connect cart overview
- Connect success/error pages
- Don't let the user move to step two before filling out all the required fields for step one

**Comment by koleCar** [comment]
@flauc 
- [ ] change value of number of items in shock
