### ISSUE TITLE
Customers page implementation

### ISSUE THREAD

**Issue by koleCar** [Jaspero/fireshop#48]

**Comment by flauc** [comment]
@koleCar we need to clean up the customer interface as well.

**Comment by flauc** [comment]
- [ ] Let's show customer avatars in the table
- [ ] We need a very similar interface for viewing the customer's information to what the customer can see on his profile when logged in.

**Comment by Siclol** [comment]
@svendjanis 

- [ ] Customer stats shouldn't be visible when creating a new customer, only on edit.
- [ ] On overview page, Customer info button should lead back to customer single page.
- [ ] Connect Wishlist, Orders, Reviews to overview page.
- [ ] Clicking on wishlist item is a routerlink to that product.
- [ ] Clicking on order is a routerlink to that single order.
- [ ] Clicking on review is a routerlink to that single review. @flauc we don't have a single-review page

**Comment by flauc** [comment]
@Siclol @svendjanis 

- [ ] We don't have any information indicating what customer is being viewed on the stats page.
