### ISSUE TITLE
Order creation

### ISSUE THREAD

**Issue by koleCar** [Jaspero/fireshop#52]
We should be able to create single order on dashboard simmilar to shop

**Comment by flauc** [comment]
@koleCar we need to clean up the order interface as well. It should be placed in the `client/shared` folder and adjusted to what the document now looks like.

**Comment by flauc** [comment]
nvm, I did it :)

**Comment by flauc** [comment]
@koleCar 

- [ ] I can move to step two without filling the credit card field
- [ ] I can click on purchase without agreeing to terms and conditions. 
- [ ] I'm not logged in but I still have a checkbox for saving my billing information. This should only be present when I'm logged in. 

@Siclol 
- [ ] There should be a link to the terms of service in that checkbox
- [ ] I think the summary of the order should be a bit clearer perhaps aligning the prices so it looks more like a receipt.
- [ ] I'm logged in but I still see this
```
Checkout: out as guest
Payment method: visa ending in 69
email: pero@pero.com
```

@koleCar 
@Siclol 

- [ ] I should be able to login/signup from the checkout page
- [ ] It looks like a lot of the intended fields aren't connected

**Comment by koleCar** [comment]
@flauc we need to create async  validator that prevens move to next step id card is invalid

**Comment by koleCar** [comment]
@flauc on route change we call save function few times
