### ISSUE TITLE
Profile image does not overwrite as intended

### ISSUE THREAD

**Issue by koleCar** [Jaspero/fireshop#56]

**Comment by koleCar** [comment]
@Siclol profile image needs to be adjusted

**Comment by flauc** [comment]
@koleCar It doesn't look like firestore does this automatically. When a user uploads a new photo we need to check the `profileImage` property he currently has and if it's from our storage we need to remove it before adding a new one.

**Comment by koleCar** [comment]
@Siclol logic works perfectly now, we just need to implement some sort of load to let the user know chosen image is uploading.
i created loading class in profile.component.scss that needs to be styled in some sort of loader/buffer with pointer-events: none
