### ISSUE TITLE
Social sharing on single product

### ISSUE THREAD

**Issue by flauc** [Jaspero/fireshop#61]
- [x] Facebook
- [x] Twitter
- [x] Email

We need to make sure all the appropriate open graph meta properties are added.

**Comment by svendjanis** [comment]
https://gitlab.com/glycan-age/website/blob/master-hr/src/app/modules/blog/blog.module.ts

**Comment by flauc** [comment]
@svendjanis 

The email share also needs to have body content. It would also be clearer to have this in a getter function on the component.
