### ISSUE TITLE
Discounts

### ISSUE THREAD

**Issue by flauc** [Jaspero/fireshop#75]
## Discount
- [x] A discount can be on a flat amount or on a percentage. We need to have a toggle for switching between those two options
- [x] It can also be limited to a number of orders or unlimited
- [x] It can have a start or end date
- [x] There should also be a toggle for showing on a ribbon on a product or not. 
- [x] There should also be a toggle for active/inactive
- [x] Toggle for determining if a notification should be sent to users with product on wishlist

## Product
- [x] products should have a select to attach an active discount to them.

## Functions
- [ ] Add a product update listener looking at a discount that sends a notification to users with that product on wishlist

**Comment by svendjanis** [comment]
![image](https://user-images.githubusercontent.com/42269262/58178904-5ccf8f80-7ca7-11e9-8915-116dc5d3eb17.png)
