### ISSUE TITLE
Import Functionality

### ISSUE THREAD

**Issue by flauc** [Jaspero/fireshop#8]
- [ ] Firestore HTTPS function that accepts a csv file in the body and a collection as a query param. Parse the csv and import all valid documents into the collection. 
- [ ] Implement file upload on the `ListComponent` and all the List pages on the Dashboard

**Comment by koleCar** [comment]
@Siclol we need style for overveiw component. i left test button on cetegories.component.html so you can test it. just remove it before merge

**Comment by koleCar** [comment]
@flauc we need to look up clear of selection after we remove items from the list
